### ISSUE TITLE
Infinite loop in exercise in chapter 3?

### ISSUE THREAD

**Issue by keenanandrew** [PacktPublishing/Machine-Learning-Engineering-with-Python-Second-Edition#65]
I think the following cell from the Jupyter notebook in [Chapter 3](Chapter03/edition2-alibi-detect-examples/ed2-alibi-detect-ch3.ipynb) has a few issues:

- There's no `reset()` method in MMDDrift, I think this should be `reset_state()`
- The function doesn't use the window_size provided as an argument
- The `while True` loop runs indefinitely

I'm new to this so I could be wrong, but I haven't been able to get this to function. 

```
def time_run(cd, X, window_size):
    n = X.shape[0]
    perm = np.random.permutation(n)
    t = 0
    cd.reset()
    while True:
        pred = cd.predict(X[perm[t%n]])
        if pred['data']['is_drift'] == 1:
            return t
        else:
            t += 1
```

The following cell also has a confusing comment and uses something called `X_h0` which isn't referenced up until that point.

**Comment by AndyMc629** [comment]
After a quick investigation I've found a couple things:

1. Can I confirm you are using [this notebook](https://github.com/PacktPublishing/Machine-Learning-Engineering-with-Python-Second-Edition/blob/main/Chapter03/drift/edition2-alibi-detect-examples/ed2-alibi-detect-ch3.ipynb)? 
2. I think that the environment setup is a bit confusing, I have a yaml for the alibi detect examples specifically and they seem to be having issues, very resolvable and I'll try bring it together into main yaml.
3. I don't think that the function is an infinite loop necessarily, it just runs until it detects some drift,  which with the settings and dataset should happen eventually! it just seems to be that when n_runs=5 that 5th instance takes a long time to run. When I set n_runs=4 we get an answer right away. I will try and introduce a max_time or something.
4. For the X_h0, where are you seeing that? I only see it in a comment so don't worry about it if that's the only place!

```python
n_runs = 4
#times_h0 = [time_run(cd, X_h0, window_size) for _ in range(n_runs)]
times_h0 = [time_run(cd, X_ref, window_size) for _ in range(n_runs)] #changed to X_ref just to run a test, change back!


print(f"Average run-time under no-drift: {np.mean(times_h0)}")
_ = scipy.stats.probplot(np.array(times_h0), dist=scipy.stats.geom, sparams=1/ert, plot=plt)
```
